<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.DotNet.Arcade.Sdk" />

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/neox-technology/aspire</PackageProjectUrl>
    <RepositoryUrl>https://github.com/neox-technology/aspire</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <!-- Prefer false here; set IsPackable=true only on Shipping projects -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
