<Project Sdk="Aspire.AppHost.Sdk/13.2.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6ae160db-156f-46dd-a234-3c2b11366d92</UserSecretsId>
  </PropertyGroup>

</Project>
