// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer.Data;

#nullable disable

namespace Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer.Data.Migrations.Secondary
{
    [DbContext(typeof(SecondaryDbContext))]
    partial class SecondaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer.Data.SecondarySampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Samples", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
