using System.Collections.Generic;
using System.Text;
using System.Text.Json;

namespace Neox.Aspire.Hosting.Auth.EntraId.Generators.Internal;

/// <summary>
/// Pure catalogue → C# emission helpers (unit-testable without a Roslyn driver).
/// </summary>
public static class MicrosoftGraphPermissionsCodeGen
{
    public const string MicrosoftGraphAppId = "00000003-0000-0000-c000-000000000000";

    public static PermissionsCatalogModel ParseCatalog(string json)
    {
        using var document = JsonDocument.Parse(json);
        var root = document.RootElement;
        var catalog = new PermissionsCatalogModel
        {
            AppId = GetString(root, "appId"),
        };

        if (string.IsNullOrWhiteSpace(catalog.AppId))
        {
            catalog.AppId = MicrosoftGraphAppId;
        }

        if (root.TryGetProperty("delegated", out var delegated) && delegated.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in delegated.EnumerateArray())
            {
                var entry = ReadEntry(item);
                if (entry is not null)
                {
                    catalog.Delegated.Add(entry);
                }
            }
        }

        if (root.TryGetProperty("application", out var application) && application.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in application.EnumerateArray())
            {
                var entry = ReadEntry(item);
                if (entry is not null)
                {
                    catalog.Application.Add(entry);
                }
            }
        }

        return catalog;
    }

    public static string Generate(PermissionsCatalogModel catalog)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Neox.Aspire.Hosting.Auth;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Source-generated Microsoft Graph well-known API permissions.</summary>");
        sb.AppendLine("public static class MicrosoftGraph");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Microsoft Graph application (client) id.</summary>");
        sb.AppendLine("    public const string AppId = \"" + EscapeCSharp(catalog.AppId) + "\";");
        sb.AppendLine();
        AppendNestedClass(sb, "Delegated", "Scope", catalog.Delegated);
        sb.AppendLine();
        AppendNestedClass(sb, "Application", "Role", catalog.Application);
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string ToPropertyName(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "Permission";
        }

        var sb = new StringBuilder();
        var upper = true;
        foreach (var c in value)
        {
            if (!char.IsLetterOrDigit(c))
            {
                upper = true;
                continue;
            }

            if (sb.Length == 0 && char.IsDigit(c))
            {
                sb.Append('P');
            }

            if (upper && char.IsLetter(c))
            {
                sb.Append(char.ToUpperInvariant(c));
                upper = false;
            }
            else
            {
                sb.Append(c);
            }
        }

        if (sb.Length == 0)
        {
            return "Permission";
        }

        var name = sb.ToString();
        if (IsReservedKeyword(name))
        {
            return name + "_";
        }

        return name;
    }

    private static void AppendNestedClass(
        StringBuilder sb,
        string className,
        string accessType,
        IReadOnlyList<PermissionEntryModel> entries)
    {
        sb.AppendLine("    /// <summary>Microsoft Graph " + className.ToLowerInvariant() + " permissions.</summary>");
        sb.AppendLine("    public static class " + className);
        sb.AppendLine("    {");

        var usedNames = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var entry in entries)
        {
            if (!entry.IsEnabled)
            {
                continue;
            }

            var propertyName = AllocatePropertyName(entry.Value, usedNames);
            var summary = string.IsNullOrWhiteSpace(entry.DisplayName)
                ? entry.Value
                : entry.Value + " — " + entry.DisplayName;
            var remarks = string.IsNullOrWhiteSpace(entry.Description)
                ? null
                : entry.Description;

            sb.AppendLine("        /// <summary>" + EscapeXml(summary) + "</summary>");
            if (remarks is not null)
            {
                sb.AppendLine("        /// <remarks>" + EscapeXml(remarks) + "</remarks>");
            }

            sb.AppendLine(
                "        public static WellKnownApiPermission " + propertyName +
                " { get; } = new(AppId, new System.Guid(\"" + entry.Id.ToString("D") + "\"), \"" +
                accessType + "\", \"" + EscapeCSharp(entry.Value) + "\");");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
    }

    private static string AllocatePropertyName(string value, HashSet<string> usedNames)
    {
        var baseName = ToPropertyName(value);
        var candidate = baseName;
        var suffix = 2;
        while (!usedNames.Add(candidate))
        {
            candidate = baseName + suffix.ToString();
            suffix++;
        }

        return candidate;
    }

    private static PermissionEntryModel? ReadEntry(JsonElement item)
    {
        var idText = GetString(item, "id");
        var value = GetString(item, "value");
        if (string.IsNullOrWhiteSpace(idText) || string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        if (!System.Guid.TryParse(idText, out var id) || id == System.Guid.Empty)
        {
            return null;
        }

        var isEnabled = !item.TryGetProperty("isEnabled", out var enabled) ||
                        enabled.ValueKind != JsonValueKind.False;

        return new PermissionEntryModel
        {
            Id = id,
            Value = value,
            DisplayName = GetString(item, "displayName"),
            Description = GetString(item, "description"),
            IsEnabled = isEnabled,
        };
    }

    private static string GetString(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString() ?? ""
            : "";

    private static string EscapeCSharp(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeXml(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    private static bool IsReservedKeyword(string name) =>
        name is "event" or "class" or "string" or "object" or "int" or "bool" or "byte" or
            "char" or "decimal" or "double" or "float" or "long" or "short" or "void" or
            "namespace" or "using" or "static" or "public" or "private" or "internal" or
            "protected" or "abstract" or "virtual" or "override" or "sealed" or "readonly" or
            "const" or "new" or "base" or "this" or "typeof" or "sizeof" or "null" or
            "true" or "false" or "default" or "if" or "else" or "for" or "foreach" or
            "while" or "do" or "switch" or "case" or "break" or "continue" or "return" or
            "throw" or "try" or "catch" or "finally" or "lock" or "fixed" or "unchecked" or
            "checked" or "unsafe" or "volatile" or "ref" or "out" or "in" or "params" or
            "where" or "select" or "from" or "group" or "into" or "orderby" or "join" or
            "let" or "ascending" or "descending" or "by" or "on" or "equals" or "async" or
            "await" or "yield" or "partial" or "record" or "init" or "required" or "file" or
            "scoped" or "var" or "dynamic" or "delegate" or "enum" or "interface" or
            "struct" or "operator" or "implicit" or "explicit" or "extern" or "goto";
}

public sealed class PermissionsCatalogModel
{
    public string AppId { get; set; } = MicrosoftGraphPermissionsCodeGen.MicrosoftGraphAppId;
    public List<PermissionEntryModel> Delegated { get; } = new List<PermissionEntryModel>();
    public List<PermissionEntryModel> Application { get; } = new List<PermissionEntryModel>();
}

public sealed class PermissionEntryModel
{
    public System.Guid Id { get; set; }
    public string Value { get; set; } = "";
    public string DisplayName { get; set; } = "";
    public string Description { get; set; } = "";
    public bool IsEnabled { get; set; } = true;
}
