<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="$(AspireVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="$(MSTestVersion)" />
    <PackageReference Include="MSTest.TestFramework" Version="$(MSTestVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\apphost\Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer.AppHost.csproj" />
    <ProjectReference Include="..\data\Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer.Data.csproj" />
    <ProjectReference Include="..\service-defaults\Neox.Aspire.EntityFrameworkCore.MigrationWorker.Tests.SqlServer.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
