<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsUnitTestProject>true</IsUnitTestProject>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Neox.Aspire.Hosting.Auth.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\hosting\Neox.Aspire.Hosting.Auth\Neox.Aspire.Hosting.Auth.csproj" />
  </ItemGroup>
</Project>
