<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsUnitTestProject>true</IsUnitTestProject>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Neox.Aspire.Hosting.Auth.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\hosting\Neox.Aspire.Hosting.Auth.EntraId\Neox.Aspire.Hosting.Auth.EntraId.csproj" />
    <ProjectReference Include="..\..\src\hosting\Neox.Aspire.Hosting.Auth.EntraId.Generators.Internal\Neox.Aspire.Hosting.Auth.EntraId.Generators.Internal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="sample-apphost/**" />
    <Compile Remove="sample-blazor/**" />
    <Compile Remove="sample-ops/**" />
    <Content Remove="sample-apphost/**" />
    <Content Remove="sample-blazor/**" />
    <Content Remove="sample-ops/**" />
    <None Remove="sample-apphost/**" />
    <None Remove="sample-blazor/**" />
    <None Remove="sample-ops/**" />
    <None Include="sample-apphost/**" />
    <None Include="sample-blazor/**" />
    <None Include="sample-ops/**" />
  </ItemGroup>
</Project>
