<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsUnitTestProject>true</IsUnitTestProject>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Neox.Azure.Provisioning.Graph.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\provisioning\Neox.Azure.Provisioning.Graph\Neox.Azure.Provisioning.Graph.csproj" />
    <ProjectReference Include="..\..\src\provisioning\Neox.Azure.Provisioning.Graph.Generators.Internal\Neox.Azure.Provisioning.Graph.Generators.Internal.csproj" />
    <None Include="..\..\src\provisioning\Neox.Azure.Provisioning.Graph\generated\types.json" CopyToOutputDirectory="PreserveNewest" Link="types.json" />
  </ItemGroup>
</Project>
