using System.Collections.Generic;
using System.Text;
using System.Text.Json;

namespace Neox.Aspire.Hosting.Azure.CustomDomains.Generators;

/// <summary>
/// Pure catalogue → C# emission helpers (unit-testable without a Roslyn driver).
/// </summary>
public static class DomainOpsProviderCodeGen
{
    public static IReadOnlyList<ProviderModel> ParseCatalog(string json)
    {
        using var document = JsonDocument.Parse(json);
        if (!document.RootElement.TryGetProperty("providers", out var providersElement) ||
            providersElement.ValueKind != JsonValueKind.Array)
        {
            return System.Array.Empty<ProviderModel>();
        }

        var list = new List<ProviderModel>();
        foreach (var providerElement in providersElement.EnumerateArray())
        {
            var entry = new ProviderModel
            {
                Slug = GetString(providerElement, "slug"),
                MethodName = GetString(providerElement, "methodName"),
                ProviderClass = GetString(providerElement, "providerClass"),
                DockerImage = GetString(providerElement, "dockerImage"),
            };

            if (string.IsNullOrWhiteSpace(entry.MethodName))
            {
                continue;
            }

            if (providerElement.TryGetProperty("settings", out var settingsElement) &&
                settingsElement.ValueKind == JsonValueKind.Array)
            {
                foreach (var settingElement in settingsElement.EnumerateArray())
                {
                    entry.Settings.Add(new SettingModel
                    {
                        YamlName = GetString(settingElement, "yamlName"),
                        Kind = GetString(settingElement, "kind"),
                        Required = settingElement.TryGetProperty("required", out var required) && required.GetBoolean(),
                        DefaultValue = settingElement.TryGetProperty("defaultValue", out var def) && def.ValueKind == JsonValueKind.String
                            ? def.GetString()
                            : null,
                        PropertyName = GetString(settingElement, "propertyName"),
                    });
                }
            }

            list.Add(entry);
        }

        return list;
    }

    public static string GenerateInterface(IReadOnlyList<ProviderModel> providers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Aspire.Hosting.ApplicationModel;");
        sb.AppendLine();
        sb.AppendLine("namespace Neox.Aspire.Hosting.Azure;");
        sb.AppendLine();
        sb.AppendLine("public partial interface IDomainOpsProviderBuilder");
        sb.AppendLine("{");
        foreach (var p in providers)
        {
            sb.AppendLine("    /// <summary>Configures " + EscapeXml(p.MethodName) + " as the OctoDNS target provider.</summary>");
            sb.AppendLine("    IResourceBuilder<" + p.MethodName + "DomainOpsProviderResource> " + p.MethodName + "(" + p.MethodName + "DomainOpsProviderOptions? options = null);");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateBuilderMethods(IReadOnlyList<ProviderModel> providers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable ASPIREPIPELINES001");
        sb.AppendLine("using Aspire.Hosting.ApplicationModel;");
        sb.AppendLine();
        sb.AppendLine("namespace Neox.Aspire.Hosting.Azure;");
        sb.AppendLine();
        sb.AppendLine("public static partial class DomainOpsProviderExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    private sealed partial class DomainOpsProviderBuilder");
        sb.AppendLine("    {");

        foreach (var p in providers)
        {
            sb.AppendLine("        public IResourceBuilder<" + p.MethodName + "DomainOpsProviderResource> " + p.MethodName + "(" + p.MethodName + "DomainOpsProviderOptions? options = null)");
            sb.AppendLine("        {");
            sb.AppendLine("            options ??= new " + p.MethodName + "DomainOpsProviderOptions();");
            sb.AppendLine("            var resource = new " + p.MethodName + "DomainOpsProviderResource(name);");
            sb.AppendLine();

            foreach (var setting in p.Settings)
            {
                if (string.Equals(setting.Kind, "literal", System.StringComparison.OrdinalIgnoreCase))
                {
                    if (!string.IsNullOrEmpty(setting.DefaultValue))
                    {
                        var defaultLiteral = ToCSharpStringLiteral(setting.DefaultValue!);
                        var local = Camel(setting.PropertyName);
                        sb.AppendLine("            var " + local + " = string.IsNullOrWhiteSpace(options." + setting.PropertyName + ") ? " + defaultLiteral + " : options." + setting.PropertyName + ";");
                        sb.AppendLine("            resource.SetLiteral(\"" + setting.YamlName + "\", " + local + ");");
                    }
                    else
                    {
                        sb.AppendLine("            if (!string.IsNullOrWhiteSpace(options." + setting.PropertyName + "))");
                        sb.AppendLine("            {");
                        sb.AppendLine("                resource.SetLiteral(\"" + setting.YamlName + "\", options." + setting.PropertyName + ");");
                        sb.AppendLine("            }");
                    }
                }
                else if (setting.Required)
                {
                    sb.AppendLine("            BindSecret(resource, \"" + setting.YamlName + "\", options." + setting.PropertyName + ", secret: true);");
                }
                else
                {
                    sb.AppendLine("            if (options." + setting.PropertyName + " is not null)");
                    sb.AppendLine("            {");
                    sb.AppendLine("                resource.BindAuthParameter(\"" + setting.YamlName + "\", options." + setting.PropertyName + ".Resource);");
                    sb.AppendLine("            }");
                }
            }

            sb.AppendLine();
            sb.AppendLine("            return AddProviderResource(resource);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateProviderTypes(ProviderModel provider)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Aspire.Hosting.ApplicationModel;");
        sb.AppendLine();
        sb.AppendLine("namespace Neox.Aspire.Hosting.Azure;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>OctoDNS " + EscapeXml(provider.MethodName) + " provider resource.</summary>");
        sb.AppendLine("public sealed class " + provider.MethodName + "DomainOpsProviderResource : DomainOpsProviderResource");
        sb.AppendLine("{");
        sb.AppendLine("    public " + provider.MethodName + "DomainOpsProviderResource(string name)");
        sb.AppendLine("        : base(name)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override string ProviderClass => \"" + EscapeCSharp(provider.ProviderClass) + "\";");
        sb.AppendLine();
        sb.AppendLine("    public override string DefaultDockerImage => \"" + EscapeCSharp(provider.DockerImage) + "\";");
        sb.AppendLine();
        sb.AppendLine("    public override string ProviderSlug => \"" + EscapeCSharp(provider.Slug) + "\";");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Optional " + EscapeXml(provider.MethodName) + " auth / settings bindings for <see cref=\"IDomainOpsProviderBuilder." + provider.MethodName + "\"/>.</summary>");
        sb.AppendLine("public sealed class " + provider.MethodName + "DomainOpsProviderOptions");
        sb.AppendLine("{");

        foreach (var setting in provider.Settings)
        {
            if (string.Equals(setting.Kind, "literal", System.StringComparison.OrdinalIgnoreCase))
            {
                var defaultInit = setting.DefaultValue is null
                    ? " = \"\";"
                    : " = " + ToCSharpStringLiteral(setting.DefaultValue) + ";";
                sb.AppendLine("    /// <summary>OctoDNS YAML setting <c>" + EscapeXml(setting.YamlName) + "</c>.</summary>");
                sb.AppendLine("    public string " + setting.PropertyName + " { get; set; }" + defaultInit);
                sb.AppendLine();
            }
            else
            {
                var requiredNote = setting.Required
                    ? "When null, a parameter named <c>{resource}-" + setting.YamlName.Replace("_", "-") + "</c> is created."
                    : "Optional; only bound when explicitly provided.";
                sb.AppendLine("    /// <summary>OctoDNS YAML setting <c>" + EscapeXml(setting.YamlName) + "</c>. " + requiredNote + "</summary>");
                sb.AppendLine("    public IResourceBuilder<ParameterResource>? " + setting.PropertyName + " { get; set; }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetString(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString() ?? ""
            : "";

    private static string Camel(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);

    private static string ToCSharpStringLiteral(string value) =>
        "\"" + EscapeCSharp(value) + "\"";

    private static string EscapeCSharp(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeXml(string value) =>
        value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}

public sealed class ProviderModel
{
    public string Slug { get; set; } = "";
    public string MethodName { get; set; } = "";
    public string ProviderClass { get; set; } = "";
    public string DockerImage { get; set; } = "";
    public List<SettingModel> Settings { get; } = new List<SettingModel>();
}

public sealed class SettingModel
{
    public string YamlName { get; set; } = "";
    public string Kind { get; set; } = "";
    public bool Required { get; set; }
    public string? DefaultValue { get; set; }
    public string PropertyName { get; set; } = "";
}
