<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>Neox.Aspire.Hosting.Azure.CustomDomains.Tests.SampleAppHost</RootNamespace>
    <UserSecretsId>d60b8300-0516-4732-8014-353b1c6754f0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" Version="$(AspireVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\hosting\Neox.Aspire.Hosting.Azure.CustomDomains\Neox.Aspire.Hosting.Azure.CustomDomains.csproj" IsAspireProjectResource="false" />
  </ItemGroup>
</Project>
